
version: "3.7"
services:
  #Laravel App
  app:
    build:
      args:
        user: boguslaw
        uid: 8888
      context: ./
      dockerfile: Dockerfile
    image: parser-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - parser

    #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: parser-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - parser

  #Mysl Service
  db:
    image: mysql:5.7
    container_name: parser-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - parser

networks:
  parser:
    driver: bridge
