
version: "3.7"
services:
  #Laravel App
  app:
    build:
      args:
        user: boguslaw
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: parser-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - parser

    #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: parser-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - parser

  #Mysl Service
  mysql:
    image: mysql:8
    container_name: parser-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: parser
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: parser
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - parser

#  redis:
#    image: redis:6.2.1-buster
#    container_name: redis
#    restart: unless-stopped
#    tty: true
#    volumes:
#      - ./redis/data:/data
#    networks:
#      - parser

  phpmyadmin:
    image: phpmyadmin:5.1.0-apache
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8200:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: parser
      PMA_PASSWORD: password
    networks:
      - parser

networks:
  parser:
    driver: bridge
